# Generated by Django 4.0 on 2021-12-17 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_todo_delete_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='Task',
        ),
    ]
